---

###
### Enable sudo (required for docker service)
###
sudo: required


###
### Language
###
language: python


###
### Add services
###
services:
  - docker


###
### Build Matrix
###
env:
  matrix:
    - ansible=2.4
    - ansible=2.5
    - ansible=2.6
    - ansible=2.7
    - ansible=2.8
    - ansible=latest


###
### Install requirements
###
install:
  # Get newer docker version
  - while ! sudo apt-get update; do sleep 1; done
  - while ! sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce; do sleep 1; done
  - docker version


###
### Linting and pre-flight check
###
before_script:
  - while ! make lint ANSIBLE_VERSION=${ansible}; do sleep 1; done
  - while ! make galaxy; do sleep 1; done


###
### Tests
###
script:
  - while ! make test ANSIBLE_VERSION=${ansible};do sleep 1; done


###
### Notify Ansible Galaxy to pull changes
###
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
