---

language: python
python: "2.7"


###
### Use fast infrastructure
###
sudo: false


###
### What travis packages are required
###
addons:
  apt:
    packages:
      - python-pip


###
### Build stage variables
###
env:
  matrix:
    - check=ansible-galaxy
    - check=syntax-check
    - check=template-generation


###
### Install requirements
###
install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' > ansible.cfg


###
### Script with Build stages
###
script:
  - if [ "${check}" = "ansible-galaxy" ]; then
        ansible-galaxy install cytopia.cloudformation
    elif [ "${check}" = "syntax-check" ]; then
        ansible-playbook tests/test.yml -i tests/inventory --syntax-check
    elif [ "${check}" = "template-generation" ]; then
        ansible-playbook tests/test.yml -i tests/inventory -vv -e cloudformation_generate_only=True
        find build/ -type f -exec cat '{}' \;
    fi


###
### Notify Ansible Galaxy to pull changes
###
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
