---
###
### Detect Drift
###
- name: detect stack drift
  command: >
    aws cloudformation detect-stack-drift
      --stack-name "{{ cloudformation.stack_name }}"
      --query="StackDriftDetectionId"
      --output=text
      {{ ('--profile ' + cloudformation.profile) if cloudformation.profile is defined and cloudformation.profile|length !=0  else '' }}
  failed_when: drift_output.rc != 0
               and not ('does not exist' in drift_output.stderr)
  check_mode: False
  changed_when: false
  register: drift_output

- name: wait for drift detection to finish
  command: >
    aws cloudformation describe-stack-drift-detection-status
      --stack-drift-detection-id="{{ drift_output.stdout }}"
      --query="DetectionStatus"
      --output=text
      {{ ('--profile ' + cloudformation.profile) if cloudformation.profile is defined and cloudformation.profile|length !=0  else '' }}
  changed_when: false
  register: drift_status
  retries: 10
  delay: 15
  until: drift_status.stdout != "DETECTION_IN_PROGRESS"
  when: drift_output.rc == 0
  check_mode: False

- name: stack drift status
  command: >
    aws cloudformation describe-stack-drift-detection-status
      --stack-drift-detection-id="{{ drift_output.stdout }}"
      --query="StackDriftStatus"
      --output=text
      {{ ('--profile ' + cloudformation.profile) if cloudformation.profile is defined and cloudformation.profile|length !=0  else '' }}
  register: drift_status
  changed_when: false
  failed_when: drift_status.stdout != "IN_SYNC"
  when: drift_output.rc == 0
  check_mode: False
